### ISSUE TITLE
Adding a Tab for the DND 3.0.3 character sheet

### ISSUE THREAD

**Issue by Twilimark** [p4535992/foundryvtt-downtime-dnd5e#11]
![image](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/47309290/813d3ff2-b67a-4b32-a11b-d86d44558c7d)

Currently, the new character sheet doesnt show a tab to see the downtime activity.

With the old sheet, it looked like this on the console.

nav class="sheet-navigation tabs" data-group="primary">
        a class="item active" data-tab="attributes">Attributes</a>
        a class="item" data-tab="inventory">Inventory</a>
        a class="item" data-tab="features">Features</a>
        a class="item" data-tab="spellbook">Spellbook</a>
        a class="item" data-tab="effects">Effects</a>
        a class="item" data-tab="biography">Biography</a>
        a class="item" data-tab="training">Downtime</a>
        a class="item" data-tab="beavers-crafting"><i class="fas fa-scroll"></i></a>
/nav
With the new sheet, it looks like this:

nav class="tabs" data-group="primary">
    a class="item control active" data-group="primary" data-tab="details" data-tooltip="DND5E.Details" aria-label="DND5E.Details">
        i class="fas fa-cog"></i>
    /a>
    <a class="item control" data-group="primary" data-tab="inventory" data-tooltip="DND5E.Inventory" aria-label="DND5E.Inventory">
        dnd5e-icon src="systems/dnd5e/icons/svg/backpack.svg"></dnd5e-icon>
    /a>
    a class="item control" data-group="primary" data-tab="features" data-tooltip="DND5E.Features" aria-label="DND5E.Features">
        i class="fas fa-list"></i>
    /a>
    a class="item control" data-group="primary" data-tab="spells" data-tooltip="TYPES.Item.spellPl" aria-label="TYPES.Item.spellPl">
        i class="fas fa-book"></i>
    /a>
    a class="item control" data-group="primary" data-tab="effects" data-tooltip="DND5E.Effects" aria-label="DND5E.Effects">
        i class="fas fa-bolt"></i>
    /a>
    a class="item control" data-group="primary" data-tab="biography" data-tooltip="DND5E.Biography" aria-label="DND5E.Biography">
        i class="fas fa-feather"></i>
    /a>
    a class="item" data-tab="beavers-crafting">
        i class="fas fa-scroll"></i>
    /a>
/nav>

**Comment by StarOfChorusim** [comment]
It would be amazing to see this followed up on! It just isn't the same without this module.

**Comment by NdranC** [comment]
Please, check and merge Forien's fix.

**Comment by p4535992** [comment]
I am in more of a hurry than you since I commissioned the thing from Forien who was kind enough to do it for me very quickly, but the free time I can devote to my projects is incredibly short . I should be able to test this weekend if Dnd5e version 3.2.0 hasn't broken something in the meantimeo.... However, I suggest you to thank @Forien to give him something on his patreon or kofi.

**Comment by NdranC** [comment]
Hey, sorry I didn't mean to sound pushy or insensitive. It was more of a bump to the issue that I quickly typed from my phone. Please take the time you need and I'm glad you are still active. Maybe because I don't use github very often but sometimes is hard to tell if something is "abandoned" or just in low activity; that's why I make these types of pokes to see if there is someone home.

Never the less thank you for the mod and thanks Forien for the contribution.

**Comment by p4535992** [comment]
No problem sorry it was not a criticism, now that I reread what I wrote in fact it could have been interpreted as such ... i ask your forgiveness, in fact i am sorry for the wait
